### ISSUE TITLE
add TLS support

### ISSUE THREAD

**Issue by lucabello** [canonical/mimir-coordinator-k8s-operator#15]
### Enhancement Proposal

The charm should support TLS through the `certificates` relation, like the other charms in the COS Lite bundle.

It should use the certificate in the **nginx** workload, so that the workers can be reached over TLS.

**Comment by Abuelodelanada** [comment]
Certificates in the *nginx* workload is one aspect of the TLS story of the coordinator.

The other side of this story is generation of [TLS config under `server` section](https://grafana.com/docs/mimir/latest/references/configuration-parameters/#server).This configuration should be generated in the coordinator charm and sent over relation data to workers.
