### ISSUE TITLE
`overrides-exporter` is missing for read-write mode

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/mimir-coordinator-k8s-operator#33]
### Enhancement Proposal

According to [Mimir documentation](https://grafana.com/docs/mimir/latest/references/architecture/deployment-modes/#read-write-mode) read-write mode needs `overrides-exporter` role.

We do not have this role in: `mimir_coordinator.py`

**Comment by Abuelodelanada** [comment]
I now [read that `overrides-exporter` is an optional component](https://grafana.com/docs/mimir/latest/references/architecture/components/overrides-exporter/)

What do you think @simskij ... should we add that component as part of our deployments?

**Comment by PietroPasotti** [comment]
IIRC I didn't add it to RECOMMENDED_DEPLOYMENT precisely because according to the official docs it's optional.
I think the right thing to do is only deploy it when the user explicitly asks for it since it doesn't seem to be part of the default offering

**Comment by IbraAoad** [comment]
We don't need `overrides-exporter` cause we don't have multi-tenancy, will close this issue.
