### ISSUE TITLE
Improve integration tests by using `sh.juju.ssh`

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/mimir-coordinator-k8s-operator#56]
Wdyt about using [`sh.juju.ssh`](https://sh.readthedocs.io/en/latest/sections/subcommands.html) instead?

_Originally posted by @sed-i in https://github.com/canonical/mimir-coordinator-k8s-operator/pull/50#discussion_r1561388166_

**Comment by lucabello** [comment]
We've considered this, but the team felt that it was diverging too much from pytest operator.
